---

- name: Actualizando los paquetes del Sistema
  dnf:
    name: "*"
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Instalando Chrony (Red Hat/Centos)
  dnf:
    name: chrony
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

# Yo soy de Lima/Perú ;)
- name: Configurando el timezone a America/Lima
  timezone:
    name: Asia/Tokyo
  become: yes
  
- name: Habilitar servicio Chronyd (Red Hat)
  systemd:
    name: chronyd
    state: started
    enabled: yes
    masked: no
  become: yes
  when: ansible_os_family == 'RedHat'

